CREATE PROCEDURE SP_GFT_CREATE_TABLE_TRADECATEGORY
@STANDARDVALUES AS BIT = 0
AS
BEGIN 

BEGIN TRY

	CREATE TABLE [DBO].[TRADECATEGORY](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[INITIALVALUE] [DECIMAL](18, 0) NOT NULL,
	[FINALVALUE] [DECIMAL](18, 0) NULL,
	[CATEGORY_ID] [INT] NOT NULL,
	[SECTOR_ID] [INT] NOT NULL
	) ON [PRIMARY]
	
	ALTER TABLE [DBO].[TRADECATEGORY]  WITH CHECK ADD  CONSTRAINT [FK_TABLECATEGORY] FOREIGN KEY([CATEGORY_ID])
	REFERENCES [DBO].[CATEGORY] ([ID])
	ALTER TABLE [DBO].[TRADECATEGORY] CHECK CONSTRAINT [FK_TABLECATEGORY]
	ALTER TABLE [DBO].[TRADECATEGORY]  WITH CHECK ADD  CONSTRAINT [FK_TABLESECTOR] FOREIGN KEY([SECTOR_ID])
	REFERENCES [DBO].[SECTOR] ([ID])
	ALTER TABLE [DBO].[TRADECATEGORY] CHECK CONSTRAINT [FK_TABLESECTOR]

	IF (@STANDARDVALUES > 0)
	BEGIN 
		INSERT INTO [DBO].[TRADECATEGORY] VALUES(0,1000000,1,1);
		INSERT INTO [DBO].[TRADECATEGORY] VALUES(1000000,NULL,2,1);
		INSERT INTO [DBO].[TRADECATEGORY] VALUES(1000000,NULL,3,2);
	END 

END TRY
BEGIN CATCH
	DECLARE @ERRORMESSAGE NVARCHAR(4000);  
    DECLARE @ERRORSEVERITY INT;  
    DECLARE @ERRORSTATE INT;  
  
    SELECT   
        @ERRORMESSAGE = ERROR_MESSAGE(),  
        @ERRORSEVERITY = ERROR_SEVERITY(),  
        @ERRORSTATE = ERROR_STATE();  
  
    RAISERROR (@ERRORMESSAGE, 
               @ERRORSEVERITY,
               @ERRORSTATE
               );  
END CATCH

END